#!/usr/bin/env bash

function main {
  local shome="${_block_shortcuts_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  exec block "${0##*/}" "$@"
}

source sub "$BASH_SOURCE" "$@"
