#!/usr/bin/env bash

function _block_shortcuts_profile {
  local shome="${_block_shortcuts_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/exec:$PATH"
}

_block_shortcuts_profile
